### ISSUE TITLE
Meteor.connect is not a function

### ISSUE THREAD

**Issue by swarthout** [aleclarson/meteor-client#2]
I tried installing meteor-client and running it as you put in the readme, but as soon as I load the javascript in the react native ios application I get a red screen saying "Meteor.connect is not a function". Do I need to add the DDP library as well? If I try requiring your DDP library, I run into an error where Xcode opens up to -_RCTSR_commonInit and highlights the line:

  assert([scheme isEqualToString:@"ws"] || [scheme isEqualToString:@"http"] || [scheme isEqualToString:@"wss"] || [scheme isEqualToString:@"https"]);

Do you have any recommendations about how to fix this? Your project sounds very intriguing and I would love to help integrate Meteor with React Native. Thank you in advance.

**Comment by aleclarson** [comment]
Whoops. Looks like you caught a blunder on my behalf. It does appear that the `ddp` library is required for `meteor-client` to work properly. I'll update the README immediately. Thanks!
1. Which version of React Native are you using?
2. What URL are you passing to `Meteor.connect`?

Cheers! :smile:

**Comment by swarthout** [comment]
I am using react-native-cli version 0.1.4 and my updated code is as follows. I changed the connect method to a data attribute because it wouldn't load otherwise.

var ddp = require('ddp');
var Meteor = require('meteor-client');
Meteor.connect = 'ws://192.168.1.100:3000/websocket';

I am still getting the error:

Assertion failed: ([scheme isEqualToString:@"ws"] || [scheme isEqualToString:@"http"] || [scheme isEqualToString:@"wss"] || [scheme isEqualToString:@"https"]), function -[RCTSRWebSocket _RCTSR_commonInit], file /Users/swarthout/Documents/meteor-react-integration/MeteorTesting/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m, line 283.

This error occurs when I add the line var ddp = require('ddp');

**Comment by aleclarson** [comment]
What's the version specified in `/Users/swarthout/Documents/meteor-react-integration/MeteorTesting/node_modules/react-native/package.json`?

**Comment by swarthout** [comment]
I have "react-native": "^0.11.2". Sorry for the miscommunication. I saw you changed the readme example and I updated my code to match. Same assertion error in Xcode.

**Comment by aleclarson** [comment]
Unfortunately I haven't had the time to test things thoroughly, which is why I have every package labeled as "experimental". I would like to get an example repo going, but I don't know when I'll be able to. So unless you're the adventurous type, you might not be able to move forward with the packages I've provided.

**Comment by swarthout** [comment]
I think this project is an interesting approach to adding Meteor to React Native apps beyond just implementing ddp. I will definitely keep an eye on this repo and contribute where I can.

**Comment by gabro** [comment]
Same thing here on react-native 0.12.0
Some more information, this crashed because `_url` is `@"file:///" in that method.

It looks like the url provided at the javascript level isn't properly passed through

**Comment by gabro** [comment]
See https://github.com/aleclarson/ddp/issues/1

@swarthout you can install the correct version using

```
npm install --save aleclarson/ddp#39ff340c5d
```

**Comment by aleclarson** [comment]
This should be fixed now.

``` sh
npm install --save aleclarson/ddp#1.2.0
```

Thanks @gabro!
